services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: churn-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/churn_db
    depends_on:
      - db

  frontend:
    build:
      context: ../churn-frontend
      dockerfile: Dockerfile
    container_name: churn-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  db:
    image: postgres:17
    container_name: churn-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: churn_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: